/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yanjin_qqfix_QQFixUtile */

#ifndef _Included_com_yanjin_qqfix_QQFixUtile
#define _Included_com_yanjin_qqfix_QQFixUtile
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yanjin_qqfix_QQFixUtile_MODE_NORMAL
#define com_yanjin_qqfix_QQFixUtile_MODE_NORMAL 0L
#undef com_yanjin_qqfix_QQFixUtile_MODE_LUOLI
#define com_yanjin_qqfix_QQFixUtile_MODE_LUOLI 1L
#undef com_yanjin_qqfix_QQFixUtile_MODE_DASHU
#define com_yanjin_qqfix_QQFixUtile_MODE_DASHU 2L
#undef com_yanjin_qqfix_QQFixUtile_MODE_JINGSONG
#define com_yanjin_qqfix_QQFixUtile_MODE_JINGSONG 3L
#undef com_yanjin_qqfix_QQFixUtile_MODE_GAOGUAI
#define com_yanjin_qqfix_QQFixUtile_MODE_GAOGUAI 4L
#undef com_yanjin_qqfix_QQFixUtile_MODE_KONGLING
#define com_yanjin_qqfix_QQFixUtile_MODE_KONGLING 5L
/*
 * Class:     com_yanjin_qqfix_QQFixUtile
 * Method:    fixVoice
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_yanjin_qqfix_QQFixUtile_fixVoice
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
